// Curated luxury hotel sanctuaries matching the new frontend design
const SEED_HOTELS = [
  {
    slug: "deluxe-room",
    name: "Deluxe Room",
    category: "Rooms",
    tagline: "Designed for effortless comfort and quiet serenity.",
    price: 340,
    size: "45 m² / 485 sq ft",
    guests: "2 Adults",
    bed: "King Bed",
    view: "Private Garden & City Skyline",
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=85",
    ],
    shortDescription:
      "A harmonious blend of warm stone textures, natural oak accents, and soft linen, crafted for restful slumber and peaceful mornings.",
    description:
      "The Deluxe Room at Hotel Relex represents the essence of modern hospitality. Furnished with custom handcrafted oak furniture, a bespoke king-size mattress adorned with 600-thread-count Egyptian cotton linens, and expansive floor-to-ceiling windows that fill the room with soft daylight. The en-suite bathroom features a walk-in rain shower clad in Italian terrazzo, complemented by artisanal botanical toiletries.",
    amenities: [
      "Plush King-size bed with Egyptian cotton",
      "Walk-in Italian rain shower",
      "Complimentary high-speed fiber Wi-Fi",
      "Nespresso coffee machine & tea atelier",
      "65-inch OLED 4K Smart TV",
      "Bespoke Diptyque bathroom amenities",
      "Curated minibar with artisan spirits",
      "Twice-daily housekeeping with turndown",
    ],
    highlights: ["Soundproof panoramic windows", "Bespoke ambient lighting controls", "Hypoallergenic feather pillows"],
  },
  {
    slug: "premium-room",
    name: "Premium Room",
    category: "Rooms",
    tagline: "Elevated aesthetics with expansive panoramic vistas.",
    price: 460,
    size: "58 m² / 624 sq ft",
    guests: "2 Adults, 1 Child",
    bed: "California King",
    view: "Panoramic Ocean Horizon",
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1600&q=85",
    ],
    shortDescription:
      "Generous living space featuring a private balcony, sculptural lounge seating, and deep soaking tub overlooking the horizon.",
    description:
      "Perched on the upper floors, our Premium Rooms offer breathtaking perspectives of the horizon. Each space includes a private furnished terrace where you can enjoy in-room breakfast as the sunrise illuminates the sky. The bathroom is a private sanctuary equipped with a freestanding soaking tub, twin marble vanities, and underfloor heating.",
    amenities: [
      "Private outdoor terrace with daybed",
      "Freestanding stone soaking tub",
      "Separate rainfall shower with steam option",
      "Bang & Olufsen Bluetooth sound system",
      "Personalized pillow menu (6 options)",
      "Daily fresh fruit and pastry service",
      "Express laundry & pressing service",
      "Dedicated 24/7 concierge assistance",
    ],
    highlights: ["Deep soaking marble tub", "Private terrace sunrise view", "Bang & Olufsen acoustics"],
  },
  {
    slug: "executive-suite",
    name: "Executive Suite",
    category: "Suites",
    tagline: "An expansive residential sanctuary for the modern traveler.",
    price: 680,
    size: "82 m² / 882 sq ft",
    guests: "3 Guests",
    bed: "Super King Bed",
    view: "Sweeping Coastal & Architectural View",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=85",
    ],
    shortDescription:
      "Distinct salon living area, executive work atelier, walk-in dressing room, and bespoke hospitality bar for seamless stays.",
    description:
      "Conceived as a private luxury residence, the Executive Suite features a secluded bedroom separated from a sun-drenched salon by bespoke sliding fluted glass screens. Host colleagues or intimate gatherings around the dining table, or unwind on the custom linen chaise lounge with a book from our curated library.",
    amenities: [
      "Separate living salon & dining area for 4",
      "Walk-in dressing room and wardrobe",
      "Executive work desk with ergonomic chair",
      "Complimentary airport VIP transfer",
      "In-suite cocktail preparation bar",
      "Dual marble vanities & walk-in wet room",
      "Priority reservations at all hotel venues",
      "Complimentary garment pressing on arrival",
    ],
    highlights: ["Separate dining & living salon", "Walk-in wardrobe", "VIP airport chauffeur included"],
  },
  {
    slug: "family-suite",
    name: "Family Suite",
    category: "Suites",
    tagline: "Refined luxury with effortless togetherness and privacy.",
    price: 820,
    size: "105 m² / 1,130 sq ft",
    guests: "4-5 Guests",
    bed: "1 King Bed + 2 Queen Beds",
    view: "Resort Gardens & Azure Waters",
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1600&q=85",
    ],
    shortDescription:
      "Two interconnected master suites, spacious central family lounge, kid-friendly luxury amenities, and dual private balconies.",
    description:
      "The Family Suite balances shared family moments with uncompromised privacy. It features two grand interconnected bedrooms, each with its own en-suite marble bathroom, flanking a generous central lounge with games and streaming entertainment. Special amenities for younger guests ensure a magical and stress-free family holiday.",
    amenities: [
      "Two private bedrooms with en-suite bathrooms",
      "Spacious central living salon with dining table",
      "Two private balconies with sun loungers",
      "Tailored children's bathrobes and welcome gifts",
      "Kitchenette with refrigerator and microwave",
      "Dedicated family concierge support",
      "Complimentary babysitting (2 hours per stay)",
      "Board game library and cinema streaming",
    ],
    highlights: ["Dual master bedrooms", "Full kitchenette & dining", "Family concierge service"],
  },
  {
    slug: "presidential-suite",
    name: "Presidential Suite",
    category: "Signature",
    tagline: "The pinnacle of architectural grandeur and bespoke privilege.",
    price: 1450,
    size: "185 m² / 1,990 sq ft",
    guests: "4 Guests",
    bed: "Palatial Emperor Bed",
    view: "360° Oceanfront & Mountain Horizon",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1600&q=85",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85",
    ],
    shortDescription:
      "Private rooftop infinity plunge pool, full butler kitchen, private sauna, grand fireplace, and 24/7 dedicated personal butler.",
    description:
      "Crowing the top floor of Hotel Relex, the Presidential Suite is an architectural masterpiece of quiet luxury. Boasting double-height ceilings, a wood-burning contemporary fireplace, a grand piano, and an expansive wraparound terrace with a heated infinity plunge pool looking out over the coastline. A dedicated private butler anticipates your every desire.",
    amenities: [
      "Private heated rooftop infinity plunge pool",
      "Private Finnish sauna and steam shower",
      "24-hour dedicated personal butler service",
      "Private chef dining service on request",
      "Grand salon with fireplace & Steinway piano",
      "Master bath in solid Carrara marble",
      "Complimentary Rolls-Royce / Maybach transfers",
      "Fully stocked premium cellar & bar",
    ],
    highlights: ["Private rooftop plunge pool", "Dedicated 24/7 butler", "Private wellness sauna"],
  },
];

module.exports = { SEED_HOTELS };
